### PR TITLE
Update packaging for python3/gtk3/systemd

### PR DESCRIPTION
**Pull request by alkisg**
This pull request aims to update the debian master branch with the following features:
- Update packaging for the newest Python3/Gtk3-based Epoptes version.
- Update epoptes and epoptes-clients versions from changelog while packaging.
- Switch from sysvinit to systemd.

### CODE REVIEW

**Comment by vagrantc** [comment]
These patches should have upstream version 1.0.0 merged before including them, so that the gtk3 and other required changes are included.

At a quick glance, the patches look ok, though I haven't tried building the package yet.

**Comment by vagrantc** [comment]
also, since the upstream version hasn't yet been released, merged, the version in debian/changelog should at least end with a ~ since it won't actually be 1.0.0-1

**Comment by alkisg** [comment]
> These patches should have upstream version 1.0.0 merged before including them, so that the gtk3 and other required changes are included.

After chatting with Vagrant in IRC about it, this step isn't needed, upstream can be merged first, and this branch later, with no conflicts involved.

> Also, since the upstream version hasn't yet been released, merged, the version in debian/changelog should at least end with a ~ since it won't actually be 1.0.0-1
> What's the purpose of this change? Isn't the upstream version sufficient? Specifically, commit 087329dc9e2ef90e01df36aacd8ea6267a3c4e29, which edits the version from debian/rules.

My understanding of the workflow:
- Me or Fotis get the upstream branch in a releaseable state, and "hand it over to you" for release.
- You do whatever changes you deem necessary and tag 1.0.0 in the upstream branch, then merge with debian/master. The upstream version isn't recorded anywhere in the source code; only in a git tag.
- You (or me like in the current pull request) update debian/* for the new release, including the version like 1.0.0-1 in debian/changelog.
- You upload to debian unstable and I upload to the Epoptes & Greek schools PPAs.

So if another distribution wanted to do an epoptes release, it'd have to have something similar to debian/rules, to update the version while building.

Is that workflow acceptable for everyone involved?

**Comment by alkisg** [comment]
> The upstream version isn't recorded anywhere in the source code

To be clear, the following two instances are just placeholders, they'll always have 1.0 (and not even 1.0.0) there, even if the actual epoptes version gets to be e.g. 2.5.0:
```
epoptes-client/epoptes-client: export VERSION="1.0"  # Automatically updated while packaging
epoptes/__init__.py: __version__ = "1.0"  # Automatically updated while packaging
```

Using debversion instead of debupstream is preferred, so that epoptes --version or the about dialog do report the correct version there. E.g. if a user reports a problem, it might help us to know that he's using 1.0.0-3 which may include some required patches, and not just 1.0.0.

**Pull request merged**
