### PR TITLE
added german comment to desktop file

### PR DESCRIPTION
**Pull request by freddii**

### CODE REVIEW

**Comment by alkisg** [comment]
Hi freddii,

the .desktop file translations happen in launchpad, see epoptes.org/translations.
It's currently translated like this:

```shell
$ grep -A2 administration po/de.po 
#~ msgid "Epoptes computer lab administration tool"
#~ msgstr "Admin-Werkzeug für Epoptes-basiertes PC-Labor"
```

If it doesn't show up in the GUI, then maybe our setup.py is using python3-distutils-extra wrong; and we should fix that; but we really shouldn't put the translations manually inside the .desktop file.

**Comment by freddii** [comment]
thanks will try do fix it there.

**Comment by alkisg** [comment]
Thank you freddii.
I think for some reason we don't ask for / include that translation anymore. This is the command to check:

```
gettext -d epoptes 'Epoptes computer lab administration tool'
```

Up to Epoptes 0.5.10, this correctly shows the translation; but in Epoptes 21.01, it doesn't.

And I think that the "~" symbol in front of the po/de.po translation, means that it's been "removed":

#~ msgstr "Admin-Werkzeug für Epoptes-basiertes PC-Labor"

This probably means that there's something wrong in the part of the code that *collects* our translation strings.

**Comment by freddii** [comment]
Yes was not able to find it in launchpad for translation.

**Pull request closed without merging**
